### ISSUE TITLE
Implement/Integrate new design

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-poba#47]
PoBA should use PoPA style

- [x] Fix get verified bank accounts
- [x] Implement bank accounts list (to verify)
- [x] Implement bank accounts list (verified)
- [x] Add unlock metamask error page
- [x] Add no deploy contract error page
- [x] Add `loadings`
- [x] Add back button
- [x] Improve HelpPage css
- [x] Improve IndexPage css
- [x] Extract common styles and remove dupplicated code in UI components

**Comment by matiasgaratortiz** [comment]
![01 - home](https://user-images.githubusercontent.com/303122/43340966-78b18502-91b4-11e8-86bd-d7b118b2c38b.png)
![02 - choose bank](https://user-images.githubusercontent.com/303122/43340968-78f60db2-91b4-11e8-9739-d9eff298bbc4.png)
![03 - bank form](https://user-images.githubusercontent.com/303122/43340969-7919033a-91b4-11e8-91e0-a521cec60f68.png)
![04 - choose bank account](https://user-images.githubusercontent.com/303122/43340967-78d213a8-91b4-11e8-9892-621e9b4395d9.png)
![05 - my bank accounts](https://user-images.githubusercontent.com/303122/43340965-788ff374-91b4-11e8-924b-67d41e10d63e.png)
