### ISSUE TITLE
Update MM references to NW

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-poba#64]

**Comment by pablofullana** [comment]
Hey @unjapones. sorry, but I'm afraid we defined this requirement when we were updating TW references from MM to NW, then the approach shifted a bit and this is outdated.

Let's remove any references to MM or NW and reference them simply as 'wallet'. Let's take current TW approach/implementation as reference. @phahulin please correct me if I'm wrong.

Once again, my apologies.

**Comment by phahulin** [comment]
Yes, let's do it this way :+1:

**Comment by unjapones** [comment]
@phahulin the people working on the Token Wizard mentioned that they worked on a similar thing [some days ago](https://github.com/poanetwork/token-wizard/pull/1110). This basically replaces the `MetaMask` text occurrences with `Wallet`.

On the other hand, we suggest the users to use Google Chrome (at least on the error page of PoBA):

> This application requires MetaMask extension for Google Chrome.
> Please make sure you are running the latest version of Google Chrome and follow this link to install MetaMask.

Do we want to be less specific about the web browser too?

**Comment by phahulin** [comment]
Yes, let's remove mention of Google Chrome.
